### ISSUE TITLE
How to contact you

### ISSUE THREAD

**Issue by QingXY57** [Alexbox364/F_Interface_AL#10]
Hi Alexbox364
  How do I contact you? Email？or Discord?

**Comment by Alexbox364** [comment]
Hi, if it’s a question about the project you can post it here so that everyone can benefit from it.
Else discord Alexbox364, but not much active.

**Comment by QingXY57** [comment]
Enable led ,OLED,TM1637,compilation will give an error for not declaring variables in advance? Or declare variables globally?
Translated by translation software

**Comment by Alexbox364** [comment]
Hi, did you well install the associated libraries in your arduino IDE ahead with library manager?

**Comment by QingXY57** [comment]
Associated libraries installed，After compiling, the prompt ：Compilation error: 'crc8Stat' was not declared in this scope

**Comment by Alexbox364** [comment]
Hi, I'll have a look

**Comment by Alexbox364** [comment]
I moved the crc8stat variable as a global variable and added pins declaration for the TM1637. Should be OK to compile. Depending on what you want to achieve with LEDs and screens, you may have to develop a bit of code.

**Comment by QingXY57** [comment]
Okay, thanks.
