### ISSUE TITLE
BOM 

### ISSUE THREAD

**Issue by maximilianschulte** [Alexbox364/F_Interface_AL#12]
Could you make the BOM's (especially for ATMEGA328P_NO_HEADER) more specific. There are some parts that are not described, espacially the crystal oscillator and the capacitors. I'd also be interested in the 12 pin connector used as the fanatec connector. I'm quiet new to all that stuff, so sorry in advance if i missed anything.

**Comment by Alexbox364** [comment]
Hi, to help you start, AliExpress kits for ATMEGA328p are a good base with included oscillator

https://a.aliexpress.com/_EJlHjkn

About the Fanatec connector you mean the QR pins of the 12x 2mm pitch pins on the PCB?

Le 30 avr. 2024 à 11:45, maximilianschulte ***@***.***> a écrit :

﻿

Could you make the BOM's (especially for ATMEGA328P_NO_HEADER) more specific. There are some parts that are not described, espacially the crystal oscillator and the capacitors. I'd also be interested in the 12 pin connector used as the fanatec connector. I'm quiet new to all that stuff, so sorry in advance if i missed anything.

**Comment by maximilianschulte** [comment]
No i mean the white connector comming from the ribbon cable. Thanks for the Atmega Kit, already ordered it.

**Comment by Alexbox364** [comment]
Ok, it’s a classical 2mm pitch JST phr connector. You have the female coming from the base.

For the male part you have to solder on the PcB (2mm pitch pin) :
https://a.aliexpress.com/_EJcDAJt
You can find straight ones or elbowed ones depending on your need.

Le 30 avr. 2024 à 14:33, maximilianschulte ***@***.***> a écrit :

﻿

No i mean the white connector comming from the ribbon cable. Thanks for the Atmega Kit, already ordered it.

**Comment by Krakane** [comment]
Hi , i don't find the 4n7001 diod for full pro micro have you a link ?

**Comment by Alexbox364** [comment]
Hi, sorry for late reply, there’s a mistake in item code, it’s 1N4001 diod

**Comment by Alexbox364** [comment]
Its role is to have a voltage drop of the 5V to 3,7v on miso line
