### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by JuanTrev24** [Alexbox364/F_Interface_AL#13]
Hello 
I made ATMEGA328P_WITH_HEADER hoping to make it work but the programming is quite difficult for me it has caused me a big headache and I would like to use my wheel but I find it impossible is there any way even just to unlock the ffb ? Is there any way to just insert the code or something like that ? 
Thanks

**Comment by JuanTrev24** [comment]
![image](https://github.com/Alexbox364/F_Interface_AL/assets/167269259/de1909a0-00c8-40d1-aada-f7df87f38374)

**Comment by Alexbox364** [comment]
Hi, for this version of the FFB unlocked, you will need to flash the code in the ATMEGA via ICSP method.

You need another arduino uno / nano / … to do this. I placed a link in the description to help you do it.

Le 2 mai 2024 à 09:40, JuanTrev24 ***@***.***> a écrit :

﻿

Hello
I made ATMEGA328P_WITH_HEADER hoping to make it work but the programming is quite difficult for me it has caused me a big headache and I would like to use my wheel but I find it impossible is there any way even just to unlock the ffb ? Is there any way to just insert the code or something like that ?
Thanks

**Comment by JuanTrev24** [comment]
Thank you for taking the time to respond to me. This is the problem I'm facing for now.![image](https://github.com/Alexbox364/F_Interface_AL/assets/167269259/6457cf64-840a-4d0b-b606-af0de3a67ff6)

**Comment by JuanTrev24** [comment]
I don't know what happened, I just know that it works.![image](https://github.com/Alexbox364/F_Interface_AL/assets/167269259/e37afeab-c512-4bcc-9ca9-ba150ee4e803)

**Comment by Alexbox364** [comment]
Hi! Good news. Problem was on uploading the code to the at mega?


Le 7 mai 2024 à 17:05, JuanTrev24 ***@***.***> a écrit :

﻿

I don't know what happened, I just know that it works.4E4BFF0F-C894-4A0F-8554-877F02FB1AF5.jpeg (view on web)<https://github.com/Alexbox364/F_Interface_AL/assets/167269259/e37afeab-c512-4bcc-9ca9-ba150ee4e803>

**Comment by Krakane** [comment]
Hi , i don't find the 4n7001 diod for full pro micro have you a link ?
