### ISSUE TITLE
On off problem with the "F_Interface_AL_v0.02" board

### ISSUE THREAD

**Issue by Garci989** [Alexbox364/F_Interface_AL#14]
Hi Alexbox364,
I'm having problems with the board because when I plug it in my CSW2.5 it connects and disconnects for 3-5 seconds and it disconncts. I've checked and uploaded the program 5 times but the result is the same. Maybe I'm jumping one step. I wish you can help me and thanks for your work

https://github.com/Alexbox364/F_Interface_AL/assets/171802651/dc92be6b-d6b1-4b3c-a0fa-17e4ce76b433

**Comment by Alexbox364** [comment]
Hello! Which version of PCB are you using?
I never had this issue. But to help understand and debug, it would be nice to have the serial port output cjecked

**Comment by Garci989** [comment]
It's the F_Interface AL vM0.02
![F_Interface_AL_Hardware_v0 02_circuit imprimé](https://github.com/Alexbox364/F_Interface_AL/assets/171802651/69ce252f-021c-4128-8506-8e9c9ee577d6)

**Comment by Garci989** [comment]
I've checked different components and when I change the step up regulator with a 5V DC input it works. I checked the step up regulator and it gives the 5V that the arduino needs. Any sugestion about it?

**Comment by Garci989** [comment]
Hi again, I've tried changing to v0_06 but I had the same problem but when I'm trying to use a nano esp32 It doesn't even compile

**Comment by Garci989** [comment]
I've tried the v0-02 and v0-06 versions even the v0-06 with the nano esp32 but 0 results. The only progress that I had is in the v0-02 jumping the step up voltage regulator but appeared the wrc wheel in screen and I couldn't press any button. No gonna lie, if I it wasn't because of the money I would be already gived up. If someone can help me I will really appreciate it.

**Comment by Garci989** [comment]
Sorry I closed it by mistake

**Comment by Garci989** [comment]
I've tried the v0-02 and v0-06 versions even the v0-06 with the nano esp32 but 0 results. The only progress that I had is in the v0-02 jumping the step up voltage regulator but appeared the wrc wheel in screen and I couldn't press any button. No gonna lie, if I it wasn't because of the money I would be already gived up. If someone can help me I will really appreciate it.

**Comment by Garci989** [comment]
![20240716_110852](https://github.com/user-attachments/assets/27c6ed20-74f8-4859-a7df-a1a96d342fde)
Sometimes it looks like it wants to do something and the start button leds start spinning but it doesn't do nothing more. Any help?

**Comment by J3161** [comment]
Bad soldering

**Comment by J3161** [comment]
Hi buddy did you figure the situation
