### ISSUE TITLE
I have another question for you, is it possible to directly use these two control buttons?

### ISSUE THREAD

**Issue by jz5588** [Alexbox364/F_Interface_AL#2]
I have another question for you, is it possible to directly use these two control buttons?
![WHAT PCB](https://github.com/Alexbox364/F_Interface_AL/assets/101662789/8c80efc0-6368-4c04-b20e-5402fe6d7faa)

**Comment by jz5588** [comment]
Because according to your tutorial, you choose the modular button

**Comment by Alexbox364** [comment]
Hi, sure, you can use them directly, they are managed independently from the 4 button groups. You’ll just need to solder the relevant resistors.
You can also use the DPAD pins as classic buttons.

**Comment by jz5588** [comment]
There are already resistors on the PCB you designed. Do I need to add another resistor if I use this button directly?

**Comment by Alexbox364** [comment]
Yes, just solder the resistors identified on the PCB. It’s just that if you don’t need specific group of functions on the PcB, you don’t need to solder all the components
