### ISSUE TITLE
Turn Racing Porsche GT3 Wheel files

### ISSUE THREAD

**Issue by Acedia5k** [Alexbox364/F_Interface_AL#4]
In Discord you said that the Turn Racing Porsche 911 GT3R Wheel is compatible with your PCB, but it needs custom CAD files. Sadly you don't answer me on there, but I need your help there.

**Comment by Alexbox364** [comment]
Hi, I did not go to discord since a long time yes. I can send you the CAD files. 
I am also working on a new version of this project with a way smaller pCB footprint that would fit in the podium hub tiny space.

**Comment by Alexbox364** [comment]
Just give me your email address in PM

**Comment by Acedia5k** [comment]
> Just give me your email address in PM

GitHub apparently removed the PM feature, and you have not listed a contact E-Mail.

**Comment by Acedia5k** [comment]
> Just give me your email address in PM

GitHub apparently removed the PM feature, and you have not listed a contact E-Mail.

**Comment by Alexbox364** [comment]
Ok, then you can PM me in discord 👍🏻

Le 30 nov. 2023 à 11:59, Acedia5k ***@***.***> a écrit :

﻿

Just give me your email address in PM

GitHub apparently removed the PM feature, and you have not listed a contact E-Mail.

**Comment by Acedia5k** [comment]
Ok you just answered my question via E Mail, I don’t know how you did that
haha.

You can send me the files here aswell 👌🏼

Alexbox364 ***@***.***> schrieb am Do. 30. Nov. 2023 um 15:37:

> Ok, then you can PM me in discord 👍🏻
>
