### ISSUE TITLE
street wheel model

### ISSUE THREAD

**Issue by Lele1494** [Alexbox364/F_Interface_AL#8]
Thank you for your great work
Sorry,My English is not good, I am using translation software to write。
I got a question,I choose the type is NANO_WHIT_HEADER.When I defined the wheel model as P-HUB,The keypad don't work,Defined as 918, kepad work's very well.How does this need to be resolved？
 BTW,Have you made this  ATTINY_NO_HEADER  ？
It's smaller，I am very interested in this project。
Thank you again for your help

**Comment by Alexbox364** [comment]
Hi, no problem 👍🏻.
Hum, that’s strange as they keypad presses are buttons presses like others. You did not change anything else in the code?
To debug it, you can observe what’s going on on the Miso SPI data by uncommenting the print_miso() function. You’ll know if the wheel actually sends d_pad data to the base.

**Comment by Alexbox364** [comment]
For the ATTINY version, I ordered the PCBs and built it. It fits very well in the base’s QR pin. So it’s mechanically OK.
I couldn’t though get it to work as SPI (actually USI) is managed in a different way than on ATMEGA chips. I sold my DD1 base a few days after completing the assembly so I couldn’t debug to its end. I wrote the code but had not enough time to mess with the USI parameters. The wheel was reacting saying the wheel needed a firmware upgrade which is quite good, better than getting in safety mode.

**Comment by Lele1494** [comment]
Thank you,I'll check it.
Even so, the 918 mode works perfectly。
I designed this, put the chips together directly, and it's being customized. I hope it works.
![3D_PCB2_2024-03-10](https://github.com/Alexbox364/F_Interface_AL/assets/149867907/c3d1b073-7bf9-491a-8995-6b42bfccca1a)

**Comment by Lele1494** [comment]
Thank you,I'll check it.
Even so, the 918 mode works perfectly。
I designed this, put the chips together directly, and it's being customized. I hope it works.
![3D_PCB2_2024-03-10](https://github.com/Alexbox364/F_Interface_AL/assets/149867907/fe021610-d0ed-4bec-9fa5-f2b88aa8f5ab)
The factory is making it, I will test whether it works.

**Comment by Lele1494** [comment]
I'm back,it works!!
3D print shell,looks very well!
Without your code, I wouldn't have been able to do it. Thank you very much!

**Comment by Lele1494** [comment]
![微信图片_20240318163203](https://github.com/Alexbox364/F_Interface_AL/assets/149867907/764e521d-4c99-446e-8980-a8b3b699f9a5)
![微信图片_20240318163207](https://github.com/Alexbox364/F_Interface_AL/assets/149867907/f500a8e4-6ad1-47dd-8eb8-25f93431ef64)

**Comment by Alexbox364** [comment]
Hi mate, this looks very cool! 
you are using an ATMEGA329P chip?
This is very tiny and can be useful for many people. Please consider sharing it on GitHub :-).
I’m working on Bluetooth based DIY and for Fanatec owners, that could be great to use you design to supply the main PcB with 5V !

**Comment by Alexbox364** [comment]
And which Fanatec wheel base do you use? 
because my last wheel was a clubsport DD 12Nm and my PCBs weren’t working with this base while they were working fine with my DD1.
Certainly a SPI timing issue.

**Comment by Lele1494** [comment]
I am still using the ancient CSW2.5，It's worked very well!
I directly remove the NANO's chip(atmega328p）and use it,Two more 1K resistors, one 16mhz crystal oscillator,one 100nf capacitor, and one LED are needed. These can all be found directly on Arduino NANO.
I have redesigned the casing, which looks more delicate and compact.

I would be happy to share my PCB files and 3d print files.
This is the pcb files.Tomorrow i will upload the 3d print files.
[F-FFB-UNLOCK.zip](https://github.com/Alexbox364/F_Interface_AL/files/14650797/F-FFB-UNLOCK.zip)

**Comment by Lele1494** [comment]
[unlock-shell.zip](https://github.com/Alexbox364/F_Interface_AL/files/14661698/unlock-shell.zip)
Here is the 3D print files.

**Comment by Alexbox364** [comment]
Hi, thank you for sharing, I’ll add the files to the repo with your credit.

**Comment by JuanTrev24** [comment]
@Lele1494 can you help me ?
